### ISSUE TITLE
Integrate DemagogTV

### ISSUE THREAD

**Issue by vlki** [Demagog2/demagog#183]
DemagogTV is now separately at https://demagogtv.cz/ . Integrate it to demagog.cz so the team can publish also in this format.

This is a big feature, it will need at least:
- updated sources administration so experts can select video to use and be able to define time marks when statements were said
- updated frontend which allows seeing the video with the statements

**Comment by vaclavbohac** [comment]
@vlki Can we close this now?

**Comment by vlki** [comment]
Oh yeah!
