### ISSUE TITLE
Allow adding new moderators

### ISSUE THREAD

**Issue by vlki** [Demagog2/demagog#211]
Right now when editing a media, you can add from existing moderators, but cannot add a new moderator.

**Comment by vlki** [comment]
Myslim, ze by nejvic davalo smysl pridat novou agendu Moderatori do sekce Kontext, kde by sly pridavat vsechny osoby. To nastavovani u jednotlivych poradu mi neprijde totiz uplne uzitecny, jak se moderatori toci a v poradech meni.

**Comment by vaclavbohac** [comment]
Ok, proc ne :-)
