### ISSUE TITLE
Unnecessary articles-segments many-to-many relation?

### ISSUE THREAD

**Issue by vlki** [Demagog2/demagog#297]
Seems like there is no need for articles-segments relation to be many-to-many, because there won't be segment, which is part of more than one article. What about we simplify that relation and have only `Article` and `ArticleSegment` models in one-to-many relation instead of current `Article`, `ArticleHasSegment` and `Segment` models? Apart from schema simplification, it would help solving #296.

@vaclavbohac What was your original reasoning behind the current many-to-many relation?

**Comment by vlki** [comment]
@vaclavbohac 🏓

**Comment by vaclavbohac** [comment]
@vlki I fully agree with you

_I honestly don't know what was the reasoning behind as I was only reverse engineering the schema from the Symfony project to rails._

Anyway it does not make sense now.

**Comment by vlki** [comment]
@vaclavbohac I see.

Could maybe Vojtech take this too? It is mostly backend issue and is closely connected to #296?
