### ISSUE TITLE
Broken migrations

### ISSUE THREAD

**Issue by vaclavbohac** [Demagog2/demagog#304]
Steps to reproduce:

1. Go to the project folder
2. Checkout latest master
3. Run `RAILS_ENV=test bin/rails db:drop db:create db:migrate`
4. Observe

Expected result:
All migrations scripts run successfuly

Actual result:
Migration (MigrationToUserAvatar, ...) scripts throw error

**Comment by vlki** [comment]
@vaclavbohac The documentation is mentioning the issue this way:
> 6.1 What are Schema Files for?
> 
> Migrations, mighty as they may be, are not the authoritative source for your database schema. That role falls to either db/schema.rb or an SQL file which Active Record generates by examining the database. They are not designed to be edited, they just represent the current state of the database.
> 
> There is no need (and it is error prone) to deploy a new instance of an app by replaying the entire migration history. It is much simpler and faster to just load into the database a description of the current schema.

From https://guides.rubyonrails.org/active_record_migrations.html#what-are-schema-files-for-questionmark

So sounds like using `db:schema:load` + `db:seed` is the intended way to setup a Rails app.
