### ISSUE TITLE
Invalid URLs

### ISSUE THREAD

**Issue by jan-martinek** [Demagog2/demagog#60]
Someone thought it's a good idea to have a comma in asset urls like this: 
`/data/diskusia/s/1513007970,4763.jpg`

Browsers can handle it, but other things break — it seems that one of them is the twitter card. FB works, but its debugger pinpoints this as a problem:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdemagog.cz%2Fdiskuze%2Fprezidentsky-duel-ceske-televize

Is it possible to url_encode the filenames or rename the files?

**Comment by JakubOnderka** [comment]
I think that easies variant is encode this character, because it works (see https://demagog.cz/data/diskusia/s/1513007970%2C4763.jpg) and we don't need change anything in old Demagog code.

**Comment by vaclavbohac** [comment]
@JakubOnderka Good idea, I'll take a look into it
